# Generated by Django 3.2.8 on 2022-02-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('codigo_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('codigo_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.IntegerField()),
                ('direccion_cliente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('codigo_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('ruc_proveedor', models.CharField(max_length=50)),
                ('Telefono_proveedor', models.IntegerField()),
                ('direccion_proveedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('cod_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('password_usuario', models.CharField(max_length=50)),
                ('nombre_completo_usuario', models.CharField(max_length=200)),
                ('tipo_usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('codigo_productos', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_productos', models.CharField(max_length=50)),
                ('preciocompra_productos', models.IntegerField()),
                ('precioventa_productos', models.IntegerField()),
                ('categoria_productos', models.IntegerField()),
                ('cantidad_productos', models.IntegerField()),
                ('nombre_proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='caja',
            fields=[
                ('codigo_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_caja', models.DateField()),
                ('hora_caja', models.TimeField()),
                ('motivo_caja', models.CharField(max_length=50, null=True)),
                ('entrada_caja', models.CharField(max_length=50, null=True)),
                ('salida_caja', models.CharField(max_length=50, null=True)),
                ('tipo_mov', models.IntegerField(null=True)),
                ('total_caja', models.CharField(max_length=50, null=True)),
                ('nombre_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.usuarios')),
            ],
        ),
    ]
