# Generated by Django 3.2.8 on 2022-02-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cod_usuario',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_usuario',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
