# Generated by Django 3.2.8 on 2022-02-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_auto_20220208_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente_audi',
            fields=[
                ('codigo_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.IntegerField()),
                ('direccion_cliente', models.CharField(max_length=50)),
                ('cod_usuario', models.IntegerField()),
                ('nombre_usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cod_usuario',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_usuario',
        ),
    ]
