# Generated by Django 3.2.8 on 2022-02-08 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_auto_20220208_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto_audi',
            fields=[
                ('codigo_productos', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_productos', models.CharField(max_length=50)),
                ('preciocompra_productos', models.IntegerField()),
                ('precioventa_productos', models.IntegerField()),
                ('categoria_productos', models.IntegerField()),
                ('cantidad_productos', models.IntegerField()),
                ('cod_usuario', models.IntegerField()),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('nombre_proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.proveedor')),
            ],
        ),
    ]
