# Generated by Django 3.2.8 on 2022-02-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_producto_audi'),
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor_audi',
            fields=[
                ('codigo_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('ruc_proveedor', models.CharField(max_length=50)),
                ('Telefono_proveedor', models.IntegerField()),
                ('direccion_proveedor', models.CharField(max_length=50)),
                ('cod_usuario', models.IntegerField()),
                ('nombre_usuario', models.CharField(max_length=50)),
            ],
        ),
    ]
